### ISSUE TITLE
Suggestion: Run promise tests

### ISSUE THREAD

**Issue by ctavan** [fluffynuts/synchronous-promise#5] opened 2017-09-21 15:56 UTC
I discovered https://github.com/promises-aplus/promises-tests today, maybe it would be worth a try to run this library against it?

**Comment by fluffynuts** [comment] 2017-09-21 19:19
Nice idea, I'll check it out (:

**Comment by fluffynuts** [comment] 2017-09-24 15:37
This would be super-cool to run, but the tests assume that the promise implementation will be asynchronous -- which is a valid consideration for a production-ready promises library, but which directly contravenes the very point for which this project was written: to provide synchronous promises for convenience during testing.

I loaded in the tests as an npm module, made the suggested adapter and ran. I get heaps of failures, all of them after mocha times out -- and the very first one to fail immediately makes it obvious that, as nice as it would be to run against these tests, it's never going to happen. Check out https://github.com/promises-aplus/promises-tests/blob/master/lib/tests/2.2.2.js#L25 -- the test there assumes that the resolution will background so that isFulfilled can be set to true before the .then() part of the promise is called (wherein the test for truth in isFulfilled is done -- and fails with synchronous-promise, because syncronous-promise, by design, won't background to allow the setting of isFulfilled before resolving).

Thanks for bringing this to my attention -- and I really wish that we could use it, but, like I say, a lot of the tests revolve around the implementation being asynchronous ): 

I considered adding an "actAsynchronous" flag to the implementation -- if it were simple enough, it would be interesting to test the library, if an asynchronous switch could be flipped. However, a cursory glance makes me believe that it's not a trivial task and I'm not entirely sure of the value, since, unless it were a simple "add a setTimeout", there would be lots of different code paths -- meaning that the original logic wouldn't be properly tested and I'd just be providing yet another implementation of a proper asynchronous promise, which, apart from being completely the opposite of the point of this project, would, imo, be a waste of time considering all of the existing great implementations, including native ES6 promises, bluebird, q, jQuery's $.deferred and all the other implementations mentioned at https://promisesaplus.com/implementations

I'll have to keep on relying on good issue reports like yours to keep this library functionally (if not temporally) equivalent to other A+ implementations.

**Closed as completed by fluffynuts** 2017-09-24 15:37 UTC
